[SPARK-11394][SQL] Throw IllegalArgumentException for unsupported types in postgresql
If DataFrame has BYTE types, throws an exception:
org.postgresql.util.PSQLException: ERROR: type "byte" does not exist

Author: Takeshi YAMAMURO <linguin.m.s@gmail.com>

Closes #9350 from maropu/FixBugInPostgreJdbc.

(cherry picked from commit 73862a1eb9744c3c32458c9c6f6431c23783786a)
Signed-off-by: Yin Huai <yhuai@databricks.com>